---
- name: Provision and Configure Flask Web App on EC2 Instance
  hosts: all
  become: yes

  vars: 
    flask_app_home: 'flask_app_CICD'
    venv_path: "/opt/flask_app/{{ flask_app_home }}/venv"
    
  tasks:
    - name: Update apt cache
      yum:
        update_cache: yes

    - name: Install required packages (Python 3, pip, git)
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git

    - name: Clean destination directory
      file:
        path: /opt/flask_app/flask_app_CICD
        state: absent

    - name: Clone Git repository
      git:
        repo: https://github.com/IfyyAguu/flask_app_CICD.git
        dest: /opt/flask_app/{{ flask_app_home }}
        version: ify-branch  # Specify the branch or tag to checkout


    - name: Create Python virtual environment
      command: python3 -m venv "{{ venv_path }}"
      vars:
        venv_path: "/opt/flask_app/{{ flask_app_home }}/venv"

    - name: Install Flask and dependencies
      pip:
        requirements: "/opt/flask_app/{{ flask_app_home }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Configure firewall (allow SSH and HTTP)
      ufw:
        rule: "{{ item }}"
        state: enabled
      loop:
        - { rule: allow, port: 22, proto: tcp }
        - { rule: allow, port: 80, proto: tcp }

    - name: Create Flask app systemd service
      template:
        src: flask_app.service.j2
        dest: /etc/systemd/system/flask_app.service
      notify: Reload systemd

    - name: Start Flask app service and enable on boot
      systemd:
        name: flask_app
        state: started
        enabled: yes

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

...
